live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[font]
# normal = { family = "MesloLGS NF", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13

[window]
decorations = "none"
